<?php

declare(strict_types=1);

use Infrangible\CatalogProductOptionDescription\Block\Product\View\Options\Description;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2025 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Php $this */
/** @var Description $block */
?>

<script type="text/x-magento-init">
    {
        "#product-options-wrapper": {
            "productOptionsDescription": {
                "descriptions": <?= /* @noEscape */ $block->getOptionsConfig(); ?>
            }
        }
    }
</script>
